blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Browser-Use GitHub
    url: https://github.com/browser-use/browser-use
    about: Main Browser-Use repository
  - name: ğŸ’¬ Discord Community
    url: https://discord.com/channels/1303749220842340412/1412240418606940170
    about: Join the #nicehack69 discussion on Discord
  - name: ğŸ¦ Follow @browser_use
    url: https://twitter.com/browser_use
    about: Twitter updates and announcements
